name: Bygg og Deploy Rekrutteringstreff-bruker
on:
  push:
  workflow_dispatch: # Legger til mulighet for manuell kj√∏ring

jobs:
  build-and-deploy:
    name: Next
    uses: navikt/toi-github-actions-workflows/.github/workflows/build-and-deploy-nextjs.yaml@v8.1
    with:
      pnpm: true
      a11y: true
      playwright: true
      playwright-github-report: true
      dev-vars-path: '.nais/dev-gcp.json'
      prod-vars-path: '.nais/prod-gcp.json'
      deploy-to-dev-if-branch-name-is: 'forbedre-tidsvisning'
      deploy-to-dev-only: true
    secrets: inherit
    permissions:
      contents: write
      id-token: write
      security-events: write
      pages: write
